#!/usr/bin/bash
## This script is under license BEER-WARE.
# "THE BEER-WARE LICENSE" (Revision 42):
# <eric@obarun.org> wrote this file.  As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think
# this stuff is worth it, you can buy me a beer in return.   Eric Vidal
shopt -s extglob
##		Shell color 

bold=$(tput bold)
reset=$(tput sgr0)
red=$(tput setaf 1)
bred=${bold}$(tput setaf 1)
green=$(tput setaf 2)
bgreen=${bold}$(tput setaf 2)
yellow=$(tput setaf 3)
byellow=${bold}$(tput setaf 3)
blue=$(tput setaf 4)
bblue=${bold}$(tput setaf 4)

## 		Some variables

config_dir=""
newroot=""
pacmanEdit=""
arch_list=""
aur_list=""
edit_custom=""
archlist=`pwd`/config
aurlist=`pwd`/config
pac_conf=`pwd`/config
customize_chroot=`pwd`/config


## 		Information display by the script 
echo_bold(){
	echo "${bold}${1}${reset}"
}
echo_info(){
	echo "${byellow}==>>${1}${reset}"
}
echo_retry(){
	echo "${bblue}==>>${1}${reset}"
}
echo_valid(){
	echo "${bgreen}==>>${1}${reset}"
}
echo_display(){
	echo "${bold}==>>${1}${reset}"
}
answer(){
	echo_retry " Please answer y or n :"
}

## 		Exit

die (){
      local message code 
      message="$1"
      [[ -n "$2" ]] && code="$2" || code=1
      if [[ -n "$message" ]] ; then
        echo "${bred}==>> Error: ${message}; exit status ${code}${reset}"
      else
        echo "${bred}==>> Error: exiting with status ${code}${reset}"
      fi
      exit 1
}

## 		Check list option

check_elements(){
	for e in "${@:2}"; do [[ $e == $1 ]] && break; done;
}

## 		Select, check editor

select_editor(){
	editors_list=("nano" "vi");
	echo_display " Select your editor :"
	select editor in "${editors_list[@]}"; do
		if check_elements "$editor" "${editors_list[@]}"; then
			echo_valid " Your editor is now : $editor"
		break
		else 
			echo_retry " Invalid option, enter 1 or 2 :"
		fi
	done
}

check_editor(){
	if [[ "$editor" == "" ]]; then
		echo_info " You need first to define your editor"
		echo_info " Please choose step 1 in the Main menu" 
		(sleep 3) && main_menu
	fi
}

## 		Select config directory

choose_dir(){
	dir_list=$(ls -U `pwd`/config/)
	echo_display " Select the directory you want to use :"
	select dir in $dir_list; do
		if check_elements "$dir" $dir_list; then
			config_dir="$dir"	 
		break
		else 
			echo_retry " Invalid number, retry :"
		fi
	done
	echo_valid " You chose $config_dir"
}

## 		Edit pacman.conf

edit_pacman(){
	check_editor
	"$editor" "$pac_conf"/"$config_dir"/pacman.conf		
}

## 		Edit customizeChroot file

edit_customize_chroot(){
	check_editor
	"$editor" "$customize_chroot"/"$config_dir"/customizeChroot
}

## 		Create temporary users for yaourt

user_tmp(){
	if [[ $(awk -F':' '{ print $1}' /etc/passwd | grep usertmp) </dev/null ]]; then
		echo_info " Create a temporary user needed to install AUR packages"
			if [[ -e /etc/sudoers ]]; then
				useradd -m -g users -G "wheel,disk,storage,optical,floppy,adm,network" -s /bin/bash usertmp || die " Impossible to create user : usertmp"
				echo "%usertmp ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
			else
				echo "${bred}==>> The file /etc/sudoers doesn't exists,"
				echo_info " Installing sudo package"
				pacman -S sudo
				user_tmp
			fi
	fi
}

##		Delete usertmp

rem_usertmp(){
	echo_info " Removing user : usertmp"
	userdel -r usertmp
	sed -i '/usertmp/d' /etc/sudoers
}
## 		Clean on exit

clean_install(){
	if [[ $(awk -F':' '{ print $1}' /etc/passwd | grep usertmp) >/dev/null ]]; then
		rem_usertmp
	else
	exit
	fi
}
		
## 		Select root directory

rootdir(){	
	echo_display " Enter your root directory :"
	read newroot
	
	until [[ -d "$newroot" ]]; do
		echo_retry " This is not a directory, please retry :"
		read newroot
	done
	
	while ! mountpoint -q "$newroot"; do
		echo_retry " This is not a valide mountpoint, please retry :"
		rootdir
	done
	
	echo_valid " Your root directory for installation is now : $newroot"
}

## Check if needed packages is installed

check_pac_needed(){
	if [[ ! $(pacman -Qs arch-install-scripts) >/dev/null ]]; then
		echo_info " Installing arch-install-scripts"
		pacman -S arch-install-scripts --config "$pac_conf"/"$config_dir"/pacman.conf || die " Impossible to install the package arch-install-scripts"
	else
		echo_valid " arch-install-scripts : already installed"
	fi
	if [[ ! $(pacman -Qs yaourt) >/dev/null ]]; then
		echo_info " Installing yaourt"
		pacman -S base-devel package-query yaourt --config "$pac_conf"/"$config_dir"/pacman.conf || die " Impossible to install the package arch-install-scripts"
	else
		echo_valid " yaourt : already installed"
	fi
}

## 		Install packages with pacman

pac_install(){
	pacman -r "$newroot" -S $(grep -h -v ^# $archlist/$config_dir/package_list/repo_*) --config "$pac_conf"/"$config_dir"/pacman.conf || die " Failed to install packages"
}

## 		Install package from aur

aur_install(){
	sudo -u usertmp yaourt -r "$newroot" -Sy $(grep -h -v ^# $aurlist/$config_dir/package_list/aur_*) || die " Failed to install packages"
}
	
## 		Create needed directory

create_dir(){
	echo_info " Create needed directory in ${newroot}"
	mkdir -m 0755 -p "$newroot"/var/{cache/pacman/pkg,lib/pacman,log} "$newroot"/{dev,run,etc}
	mkdir -m 0755 -p "$newroot"/dev/{pts,shm}
	mkdir -m 1777 -p "$newroot"/tmp
	mkdir -m 0555 -p "$newroot"/{sys,proc}
}

## 		Mounting necessary directory

mount_dir(){
	echo_info " Mounting filesystem in ${newroot}"
	mount -o nosuid,noexec,nodev -t proc proc "$newroot"/proc
	mount -o nosuid,noexec,nodev -t sysfs sys "$newroot"/sys 
	mount -o mode=0755,nosuid -t devtmpfs udev "$newroot"/dev 
	mount -o mode=0620,gid=5,nosuid,noexec -t devpts devpts "$newroot"/dev/pts 
	mount -o mode=1777,nosuid,nodev -t tmpfs shm "$newroot"/dev/shm 
	mount -o nosuid,nodev,mode=0755 -t tmpfs run "$newroot"/run 
	mount -o mode=1777,strictatime,nodev,nosuid -t tmpfs tmp "$newroot"/tmp 
}

## 		Main menu

main_menu(){

step=100

while [[ "$step" !=  10 ]]; do
	clear
	echo_bold ""
	echo_bold ""
	echo_bold "*****************************************"
	echo_bold "              Main menu"
	echo_bold "*****************************************"
	echo_bold ""
	echo_bold ""
	echo_bold " 1  -  Select Editor"
	echo_bold " 2  -  Choose the directory contening configuration files"
	echo_bold " 3  -  Edit the pacman.conf used by the script"
	echo_bold " 4  -  Edit the packages lists (AUR including) from repo defined in pacman.conf"
	echo_bold " 5  -  Edit the scripts which configure the fresh installation"
	echo_bold " 6  -  Enter your root directory of the installation"
	echo_bold " 7  -  Install the new system"
	echo_bold " 8  -  Exit installation script"
	echo_bold ""
	echo_bold ""
	echo_display " Enter your choice :";read  step
	
	## 			Define new root before install
	if [[ "$step" == 7 ]] && [[ "$step" >/dev/null ]]; then
		echo_info " You need to define the directory contening configuration files before install the system (step 2)"
		echo_display " Press enter to return to the Main menu"
		read enter
		step=100
		main_menu
	fi
	if [[ "$step" == 7 ]] && [[ "$step6" >/dev/null ]]; then
		echo_info " You need to define root directory before install the system (step 6)"
		echo_display " Press enter to return to the Main menu"
		read enter
		step=100
		main_menu
	else

		case "$step" in 
			1)	select_editor;;
			2)	choose_dir;; # Never comment this options
			3)	edit_pacman;;
			4)	select_list;;
			5)	edit_customize_chroot;;
			6)	rootdir # Never comment this options
				step6=1  # This step is done, user can choose install the system
				;; 
			7)	install_system;;	
			8)	echo_info " Exiting"
				exit;;
			*) echo_retry " Please enter a number between 1-8: "
		esac
		echo_display " Press enter to return to the Main menu"
		read enter
	fi 
done
}

select_list(){
	check_editor
	pac_list=$(ls "$pac_conf"/"$config_dir"/package_list/)
	echo_info " File named repo_* concerns the packages provides by repositories defined in pacman.conf"
	echo_info " File named aur_* concerns the packages from AUR"
	echo_display " Select the list you want to edit :"
	select list in $pac_list; do
		if check_elements "$list" $pac_list; then
			"$editor" "$pac_conf"/"$config_dir"/package_list/"$list"
		break
		else 
			echo_retry " Invalid number, retry :"
		fi
	done
}
install_system(){

user_tmp
create_dir
mount_dir

##		Copying file needed

echo_info " Copy needed file in ${newroot}"
cp /etc/resolv.conf "$newroot"/etc/resolv.conf || die " Impossible to copy the file resolv.conf"
cp "$customize_chroot"/"$config_dir"/customizeChroot "$newroot"/etc/customizeChroot || die " ${customize_chroot} do not exist"

##		Sync database

echo_info " Synchronize database and check needed packages"
pacman -r "$newroot" -Syy --config "$pac_conf"/"$config_dir"/pacman.conf || die " Impossible to synchronize database"
check_pac_needed

##		Install packages

echo_info " Install packages from lists"
pac_install || die " Impossible to install packages" 
aur_install || die " Impossible to install packages"

echo_info " Generate fstab"
genfstab -p "$newroot" >> "$newroot"/etc/fstab || die " Impossible to generate fstab"
echo_info " Copying configuration files in ${newroot}"
cp -af `pwd`/config/"$config_dir"/rootfs/* "$newroot"/ || die " Impossible to copy files"

##		Customize newroot

echo_info " Enter in chroot of ${newroot}"
chroot "$newroot" /etc/customizeChroot || die " Failed to enter in : ${newroot} or Failed to execute correctly the file"

}
